SG_HR_Portal/SG_HR_Portal.UI/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_HR_Portal.BLL;
using SG_HR_Portal.Models.DataModels;
using SG_HR_Portal.Models.ViewModels;

namespace SG_HR_Portal.UI.Controllers
{
    public class ApplicationController : Controller
    {
        // GET: Application
        [HttpGet]
        public ActionResult List()
        {
            var appManager = new ApplicationManager();
            var model = appManager.List();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult Add()
        {
            var posManager = new PositionManager();
            var viewModel = new ApplicationVM();
            viewModel.SetPositionItems(posManager.List());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(ApplicationVM applicationVM)
        {
            var posManager = new PositionManager();
            applicationVM.Application.Position = posManager.Get(applicationVM.Application.Position.PositionId);

            var appManager = new ApplicationManager();
            appManager.Add(applicationVM.Application);

            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var viewModel = new ApplicationVM();

            var appManager = new ApplicationManager();
            var application = appManager.Get(id);
            viewModel.Application = application;

            var posManager = new PositionManager();
            viewModel.SetPositionItems(posManager.List());

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ApplicationVM applicationVM)
        {

            var posManager = new PositionManager();
            applicationVM.Application.Position = posManager.Get(applicationVM.Application.Position.PositionId);

            var appManager = new ApplicationManager();
            appManager.Edit(applicationVM.Application);

            return RedirectToAction("List");

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var appManager = new ApplicationManager();
            var app = appManager.Get(id);
            return View(app);
        }

        [HttpPost]
        public ActionResult Delete(Application application)
        {
            var appManager = new ApplicationManager();
            appManager.Delete(application.ApplicationId);
            return RedirectToAction("List");
        }
    }
}

SG_HR_Portal/SG_HR_Portal.UI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_HR_Portal.BLL;
using SG_HR_Portal.Models.DataModels;

namespace SG_HR_Portal.UI.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        [HttpGet]
        public ActionResult Manage()
        {
            var catManager = new CategoryManager();
            var model = catManager.List();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new Category());
        }

        [HttpPost]
        public ActionResult Add(Category category)
        {
            if (ModelState.IsValid)
            {
                var catManager = new CategoryManager();
                catManager.Add(category);
                return RedirectToAction("Manage");
            }
            else
            {
                return View(category);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var catManager = new CategoryManager();
            var category = catManager.Get(id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            var catManager = new CategoryManager();
            catManager.Edit(category);
            return RedirectToAction("Manage");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var catManager = new CategoryManager();
            var cat = catManager.Get(id);
            return View(cat);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            var catManager = new CategoryManager();
            catManager.Delete(category.CategoryId);
            return RedirectToAction("Manage");
        }
    }
}

SG_HR_Portal/SG_HR_Portal.UI/Controllers/PolicyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_HR_Portal.BLL;
using SG_HR_Portal.Models.DataModels;
using SG_HR_Portal.Models.ViewModels;

namespace SG_HR_Portal.UI.Controllers
{
    public class PolicyController : Controller
    {
        // GET: Policy
        [HttpGet]
        public ActionResult List()
        {
            var polManager = new PolicyManager();
            var model = polManager.List();
            
            return View(model);
        }

        [HttpGet]
        public ActionResult ListAll()
        {
            var polManager = new PolicyManager();
            var model = polManager.List();
            return View(model);
        }

        [HttpGet]
        public ActionResult Manage()
        {
            var polManager = new PolicyManager();
            var model = polManager.List();
            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var catManager = new CategoryManager();
            var viewModel = new PolicyVM();
            viewModel.SetCategoryItems(catManager.List());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(PolicyVM policyVM)
        {
            var catManager = new CategoryManager();
            policyVM.Policy.PolicyCategory = catManager.Get(policyVM.Policy.PolicyCategory.CategoryId);

            var polManager = new PolicyManager();
            polManager.Add(policyVM.Policy);

            return RedirectToAction("Manage");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var viewModel = new PolicyVM();

            var polManager = new PolicyManager();
            var policy = polManager.Get(id);
            viewModel.Policy = policy;

            var catManager = new CategoryManager();
            viewModel.SetCategoryItems(catManager.List());

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(PolicyVM policyVM)
        {
            var catManager = new CategoryManager();
            policyVM.Policy.PolicyCategory = catManager.Get(policyVM.Policy.PolicyCategory.CategoryId);

            var polManager = new PolicyManager();
            polManager.Edit(policyVM.Policy);

            return RedirectToAction("Manage");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var polManager = new PolicyManager();
            var pol = polManager.Get(id);
            return View(pol);
        }

        [HttpPost]
        public ActionResult Delete(Policy policy)
        {
            var polManager = new PolicyManager();
            polManager.Delete(policy.PolicyId);
            return RedirectToAction("Manage");
        }
    }
}

SG_HR_Portal/SG_HR_Portal.UI/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SG_HR_Portal.BLL;
using SG_HR_Portal.Models.DataModels;

namespace SG_HR_Portal.UI.Controllers
{
    public class PositionController : Controller
    {
        // GET: Position
        [HttpGet]
        public ActionResult List()
        {
            var posManager = new PositionManager();
            var model = posManager.List();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(new Position());
        }

        [HttpPost]
        public ActionResult Add(Position position)
        {
            var posManager = new PositionManager();
            posManager.Add(position);
            return RedirectToAction("List");

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var posManager = new PositionManager();
            var position = posManager.Get(id);
            return View(position);
        }

        [HttpPost]
        public ActionResult Edit(Position position)
        {
            var posManager = new PositionManager();
            posManager.Edit(position);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var posManager = new PositionManager();
            var pos = posManager.Get(id);
            return View(pos);
        }

        [HttpPost]
        public ActionResult Delete(Position position)
        {
            var posManager = new PositionManager();
            posManager.Delete(position.PositionId);
            return RedirectToAction("List");
        }
    }
}

SG_HR_Portal/SG_HR_Portal.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SG HR Portal</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Software Guild HR Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Applications<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("List All", "List", "Application")</li>
                            <li>@Html.ActionLink("Submit", "Add", "Application")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Positions<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("List All", "List", "Position")</li>
                            <li>@Html.ActionLink("Add", "Add", "Position")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Policies<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("List All", "ListAll", "Policy")</li>
                            <li>@Html.ActionLink("Manage Policies", "Manage", "Policy")</li>
                            <li>@Html.ActionLink("Manage Categories", "Manage", "Category")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Site</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
    @RenderSection("scripts", required: false)
</body>
</html>